source/models/vacation.py
from models.sql_table import SqlTable
from datetime import date,datetime

class VacationModel(SqlTable):
    
    def __init__(self, vacation_id : int, vacation_info : str, country_id : int, vacation_start : date, vacation_end : date, price : int, pic_name : str):
        self.vacation_id = vacation_id
        self.vacation_info = vacation_info
        self.country_id = country_id
        self.vacation_start = vacation_start
        self.vacation_end = vacation_end
        self.price = price
        self.pic_name = pic_name


    @staticmethod
    def _dict_converter(dictionary : dict):
        vacation_id = dictionary["vacationId"]
        vacation_info = dictionary["vacationInfo"]
        country_id = dictionary["countryName"]
        vacation_start = dictionary["vacationStart"]
        vacation_end = dictionary["vacationEnd"]
        price = dictionary["price"]
        pic_name = dictionary["picName"]
        vacation = VacationModel(vacation_id, vacation_info, country_id, vacation_start, vacation_end, price, pic_name)
        return vacation
    


    def validate_create_vacation(self):
        today = datetime.today()
        vacation_start_input = datetime.strptime(self.vacation_start, '%Y-%m-%d')
        vacation_end_input = datetime.strptime(self.vacation_end, '%Y-%m-%d')
        validations = [
            (not self.country_id, "Country ID missing"),
            (not self.vacation_start, "Start date missing"),
            (not self.vacation_end, "End date missing"),
            (not self.price, "Price is missing"),
            (len(str(self.country_id)) < 1 or len(str(self.country_id)) > 2, "Country ID not valid"),
            (len(str(self.price)) < 1 or len(str(self.price)) > 5, "Price length not valid"),
            (self.price < 1 or self.price > 10000, "Price is not valid"),
            (vacation_start_input >= vacation_end_input, "Vacation start date should be before vacation end date"),
            (vacation_start_input <= today, "Vacation start date should be in the future")
        ]

        for condition, error_message in validations:
            if condition:
                return error_message
        return None


    def validate_edit_vacation(self):
        today = datetime.today()
        vacation_start_input = datetime.strptime(self.vacation_start, '%Y-%m-%d')
        vacation_end_input = datetime.strptime(self.vacation_end, '%Y-%m-%d')
        validations = [
            (not self.vacation_id, "Missing vacation ID"),
            (not self.country_id, "Country ID missing"),
            (not self.vacation_start, "Start date missing"),
            (not self.vacation_end, "End date missing"),
            (not self.price, "Price is missing"),
            (len(str(self.vacation_id)) < 1, "Vacation ID not valid"),
            (len(str(self.country_id)) < 1 or len(str(self.country_id)) > 2, "Country ID not valid"),
            (len(str(self.price)) < 1 or len(str(self.price)) > 5, "Price length not valid"),
            (self.price <= 0 or self.price > 10000, "Vacation price should be between 1 and 10000"),
            (vacation_start_input >= vacation_end_input, "Vacation start date should be before vacation end date"),
            ]
        
        
        for condition, error_message in validations:
            if condition:
                return error_message
        return None
        
        



    def __str__(self) -> str:
        return f"vacation ID: {self.vacation_id}, info: {self.vacation_info}, country id: {self.country_id}, vacation start: {self.vacation_start}, vacation end: {self.vacation_end}, price: {self.price}$, pic: {self.pic_name}"    

source/views/about_view.py
from flask import Blueprint, render_template, session


about_blueprint = Blueprint('about_view', __name__)


@about_blueprint.route("/about")
def about():
    return render_template('about.html', current_user=session.get("current_user"))

source/views/login_view.py
from flask import Blueprint, render_template, url_for, redirect, request
from facades.login_facade import LoginFacade
from models.client_error import ValidationError, AuthError
from utils.logger import Logger


auth_blueprint = Blueprint("login_view", __name__)

facade = LoginFacade()


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    try:
        if request.method == "GET":
            return render_template("register.html")
        facade.register()
        return redirect(url_for("home_view.home"))
    except ValidationError as err:
        Logger.log(err.message)
        return render_template("register.html", error=err.message, user=err.model)


@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    error = request.args.get('error')
    try:
        if request.method == "GET":
            return render_template("login.html", credentials={}, error=error)
        facade.login()
        return redirect(url_for("vacations_view.list"))
    except (ValidationError, AuthError) as err:
        Logger.log(err.message)
        return render_template("login.html", error=err.message, credentials=err.model)


@auth_blueprint.route("/logout", methods=["GET", "POST"])
def logout():
    facade.logout()
    return redirect(url_for("home_view.home"))

source/views/vacations_view.py
from flask import Blueprint,render_template,send_file,redirect,url_for,request,session
from facades.vacation_facade import VacationFacade
from facades.login_facade import LoginFacade
from facades.like_facade import LikeFacade
from utils.image_handler import ImageHandler
from utils.logger import Logger
from models.client_error import ResourceNotFoundError,ValidationError, AuthError
from models.roles import RoleModel
from models.countries import CountryModel


vacations_blueprint = Blueprint('vacations_view', __name__)
facade = VacationFacade()
login_facade = LoginFacade()
like_facade = LikeFacade()

@vacations_blueprint.route("/vacations", methods=["GET", "POST"])
def list():
    try:
        login_facade.block_anon()
        all_vacations = facade.show_all_vacations()
        like_count = like_facade.get_likes_count()
        current_user = session.get("current_user")


        user_liked_vacations = []
        if current_user:
            user_likes = like_facade.get_likes_using_user_id(current_user['userId'])
            user_liked_vacations = [like.vacation_id for like in user_likes]

        if request.method == "GET": return render_template('vacations.html', vacations=all_vacations,likes = like_count, user_liked_vacations=user_liked_vacations , current_user = current_user, admin = RoleModel.ADMIN.value, user = RoleModel.USER.value)
        like_facade.create_or_delete_like()
        return redirect(url_for("vacations_view.list"))
    except AuthError as err:
        Logger.log(err.message)
        return redirect(url_for("login_view.login", error=err.message))

@vacations_blueprint.route("/vacations/images/<string:image_name>")
def get_image(image_name):
    image_path = ImageHandler.get_image_path(image_name)
    return send_file(image_path)
    


@vacations_blueprint.route("/vacations/details/<int:vacation_id>")
def details(vacation_id):
    try:
        one_vacation = facade.get_vacation_using_id(vacation_id)
        return render_template('vacation_details.html', vacation=one_vacation, current_user = session.get('current_user'), admin = RoleModel.ADMIN.value )
    except ResourceNotFoundError as err:
        Logger.log(err.message)
        return render_template("404.html",error=err.message)

@vacations_blueprint.route("/vacations/new",methods=["GET","POST"])
def insert():
    try:
        login_facade.block_anon()
        login_facade.block_none_admin()
        if (request.method=="GET"): return render_template("insert_vacation.html", current_user = session.get('current_user'), countries = CountryModel)
        facade.create_vacation()
        return redirect(url_for("vacations_view.list"))
    except AuthError as err:
        return render_template("500.html",error=err.message)
    except ValidationError as err:
        return render_template("insert_vacation.html", error=err.message)
 


@vacations_blueprint.route("/vacations/edit/<int:vacation_id>",methods=["GET","POST"])
def edit(vacation_id):
    try:
        login_facade.block_anon()
        login_facade.block_none_admin()
        if(request.method=="GET"):
            one_vacation = facade.get_vacation_using_id(vacation_id)
            return render_template("edit_vacation.html", vacation=one_vacation,  current_user = session.get('current_user'),  countries = CountryModel)
        
        facade.update_existing_vacation()
        return redirect(url_for("vacations_view.list"))
    except AuthError as err:
        return render_template("500.html",error=err.message)
    except ValidationError as err:
        return render_template("edit_vacation.html", error=err.message)


@vacations_blueprint.route("/vacations/delete/<int:vacation_id>",methods=["GET","POST"])
def delete(vacation_id):
    login_facade.block_anon()
    login_facade.block_none_admin()
    try:
        login_facade.block_none_admin()
        facade.delete_vacation(vacation_id)
        return redirect(url_for("vacations_view.list"))
    except AuthError as err:
        return render_template("500.html",error=err.message)

source/templates/about.html
{% extends "layout.html" %}

{% block title %} About {% endblock title %}

{% block content %}
    <div class="about-container">
        <div class="about-textbox">
            <section>
                <h2>About Me</h2>
                <p>Hello! I'm Nitz, a 24-year-old from Israel. I created this Chocobo-themed vacation tours site as part of my studies at John Bryce.</p>
                <p>The inspiration for this site comes from the Final Fantasy series, a renowned franchise in the world of video games. Within this series, Chocobos are iconic, bird-like creatures often used as a mode of transportation across various terrains. These friendly and versatile creatures have become a beloved symbol of the series, representing adventure and exploration.</p>
            </section>
            
            <section>
                <h2>About the Website</h2>
                <p>My website combines the whimsical theme of Chocobos with real-world vacation tours. The site features an intuitive design, allowing users to easily browse through different tour options and discover exciting destinations.</p>
                <p>The frontend uses HTML, CSS, and JavaScript to create a visually appealing and responsive experience. The backend is powered by Python with Flask, managing user accounts, tour details, and bookings securely through a MySQL database.</p>
            </section>
            
            <section>
                <h2>Enjoy Your Visit!</h2>
            </section>
        </div>
        <img src="{{ url_for('static', filename='images/Chocotours_Logo.png') }}" alt="Chocotours Logo" class="about-logo">
    </div>
    <a href="{{ url_for('home_view.home') }}" class="back-link"> Home</a><br>
{% endblock content %}

source/templates/edit_vacation.html
{% extends "layout.html" %}

{% block title %}Edit Vacation{% endblock title %}
{% block content %}
<form method="post" class="forms" enctype="multipart/form-data" id="vacationForm">
    <div>
        <h1 class="form-title"><strong>Edit Vacation</strong><br>#{{ vacation.vacation_id }} - {{ vacation.country_id }}</h1>
    </div>
    
    <input type="hidden" value="{{ vacation.vacation_id }}" name="vacation_id" id="vacation_id" required>

    <div class="form-floating mb-3">
        <select class="form-select" name="country_id" id="country_id" required>
            {% for country_name, country in countries.__members__.items() %}
                <option value="{{ country.value }}" {% if vacation.country_id == country.value %}selected{% endif %}>
                    {{ country_name.replace('_', ' ') }}
                </option>
            {% endfor %}
        </select>
        <label for="country_id">Country</label>
    </div>
    
    <div class="form-floating mb-3">
        <textarea class="form-control" name="vacation_info" id="vacation_info" placeholder="Description" rows="10">{{ vacation.vacation_info }}</textarea>
        <label for="vacation_info">Description</label>
    </div>

    <div class="form-floating mb-3">
        <input type="date" class="form-control" value="{{ vacation.vacation_start }}" name="vacation_start" id="vacation_start" placeholder="Vacation Start Date" required>
        <label for="vacation_start">Vacation Start Date</label>
    </div>

    <div class="form-floating mb-3">
        <input type="date" class="form-control" value="{{ vacation.vacation_end }}" name="vacation_end" id="vacation_end" placeholder="Vacation End Date" required>
        <label for="vacation_end">Vacation End Date</label>
    </div>

    <div class="form-floating mb-3">
        <input type="number" class="form-control" value="{{ vacation.price }}" name="vacation_price" id="vacation_price" placeholder="Price" min="1" max="10000" required>
        <label for="vacation_price">Price</label>
    </div>

    <div class="form-floating mb-3">
        <input type="file" class="form-control" name="add_image" id="add_image" accept="image/*">
        <label for="add_image">Add Image</label>
        <div id="image_preview" class="image-preview mt-2">
            <img id="preview" src="" alt="Image Preview" style="display: none; max-width: 100%; height: auto;">
        </div>
    </div>

    <button type="submit" class="btn btn-warning w-100">Update</button>
</form>
{% endblock content %}

source/templates/index.html
{% extends "layout.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="main-content">
    <div class="text-container">
        <h1>Welcome to <em>Chocobo Tours</em> dear {{ current_user["firstName"] }} {{ current_user["lastName"] }}! {% if current_user %}{% else %}Guest{% endif %}</h1>        <h2>Your Gateway to <em>Magical Adventures</em></h2>
        <p><strong>Discover the world with a touch of fantasy and whimsy.</strong></p>
        <p>
            Inspired by the beloved <strong>Chocobos</strong> from the <em>Final Fantasy</em> series, our tours are designed to transport you to magical destinations, much like these iconic creatures do in their fantastical world.
        </p>
        <p>
            Whether you're soaring over serene landscapes or exploring vibrant cities, <em>Chocobo Tours</em> promises an experience as delightful and whimsical as the birds that inspired us.
        </p>
        <p><strong>Embark on a journey with us, and let your imagination take flight!</strong></p>
    </div>
    {% if not current_user %}
    <div class="small-container">
        <h4 class="centered-text">Fasten your seatbelt, please sign in or register!</h4>
        <div class="d-flex justify-content-between">
            <a href="{{ url_for('login_view.login') }}" class="btn btn-light btn-sm">Login</a>
            <a href="{{ url_for('login_view.register') }}" class="btn btn-primary btn-sm">Register</a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}

source/templates/insert_vacation.html
{% extends "layout.html" %}

{% block title %}Add vacation{% endblock title %}

{% block content %}
<form method="post" class="forms" enctype="multipart/form-data" id="vacationForm">
    <h1 class="form-title">New vacation</h1>
    <div class="form-floating mb-3">
        <select class="form-select" name="country_id" id="country_id" required>
            <option value="" disabled selected>Select a country</option>
            {% for country_name, country in countries.__members__.items() %}
                <option value="{{ country.value }}">
                    {{ country_name.replace('_', ' ') }}
                </option>
            {% endfor %}
        </select>
        <label for="country_id">Country</label>
    </div>
    <div class="form-floating mb-3">
        <textarea class="form-control" name="vacation_info" id="vacation_info" placeholder="Description"></textarea>
        <label for="vacation_info">Description</label>
    </div>

    <div class="form-floating mb-3">
        <input type="date" class="form-control" name="vacation_start" id="vacation_start" placeholder="vacation_start" required>
        <label for="vacation_start">Vacation Start Date</label>
    </div>

    <div class="form-floating mb-3">
        <input type="date" class="form-control" name="vacation_end" id="vacation_end" placeholder="vacation_end" required>
        <label for="vacation_end">Vacation End Date</label>
    </div>

    <div class="form-floating mb-3">
        <input type="number" class="form-control" name="vacation_price" id="vacation_price" placeholder="vacation_price" min="1" max="10000" required>
        <label for="vacation_price">Price</label>
    </div>

    <div class="form-floating mb-3">
        <input type="file" class="form-control" name="add_image" id="add_image" accept="image/*">
        <label for="add_image">Add Image</label>
        <div id="image_preview" class="image-preview mt-2">
            <img id="preview" src="" alt="Image Preview" style="display: none; max-width: 100%; height: auto;">
        </div>
    </div>

    <button type="submit" class="btn btn-warning w-100">Add</button>
</form>
{% endblock content %}

source/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/Chocotours_Favicon_16x16.png') }}"> 
</head>
<body>
<div class="layout">
    {% if error %}
        <span class="error">{{ error }}</span>
    {% endif %}
    {% if current_user %}
        <header class="navbar-container">
            {% include "navbar.html" %}
        </header>
    {% endif %}

    <main class="content-container">
        {% block content %}
            <h1>My Website</h1>
        {% endblock content %}
    </main>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

source/templates/login.html
{% extends "layout.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
<form method="post" class="forms">
    <h1 class="form-title"><strong>Login</strong></h1>
    <div class="form-floating mb-3">
        <input class="form-control" type="email" name="email" id="email" placeholder="email" value="{{ credentials.email }}" minlength="2" maxlength="30" required>
        <label for="email">Email:</label>
    </div>
    <div class="form-floating mb-3">
        <input class="form-control" type="password" name="password" id="password" placeholder="password" minlength="2" maxlength="20" required>
        <label for="password">Password:</label>
    </div>
    <button type="submit" class="btn btn-warning w-100">Login</button>
    <a href="{{ url_for('home_view.home') }}" class="back-link">Back to Home</a>
</form>
{% endblock content %}

source/templates/navbar.html
<button class="offcanvas-toggle-button" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
    <img src="{{ url_for('static', filename='images/menu.png') }}" alt="Menu Icon">
</button>


<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        {% if current_user %}
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item" id="logged-user">
                <h5><a class="nav-link custom-nav-link" href="#">{{ 'Hello ' + current_user["firstName"] + ' ' +current_user["lastName"] + '!' if current_user else 'Hello Guest!' }}</a></h5>
            </li>
            <li class="nav-item">
                <a class="nav-link custom-nav-link" href="{{ url_for('home_view.home') }}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link custom-nav-link" href="{{ url_for('vacations_view.list') }}">Vacations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link custom-nav-link" href="{{ url_for('about_view.about') }}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link custom-nav-link" href="{{ url_for('login_view.logout') }}">Log out</a>
            </li>
        </ul>
        {% endif %}
    </div>
</div>

source/templates/register.html
{% extends "layout.html" %}

{% block title %}Register{% endblock title %}

{% block content %}
<form method="post" class="forms">
    <h1 class="form-title">Register</h1>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" name="first_name" id="first_name" placeholder="first_name" minlength="2" maxlength="20" required>
        <label for="first_name">First name</label>
    </div>

    <div class="form-floating mb-3">
        <input type="text" class="form-control" name="last_name" id="last_name" placeholder="last_name" minlength="2" maxlength="20" required>
        <label for="last_name">Last name</label>
    </div>

    <div class="form-floating mb-3">
        <input type="email" class="form-control" name="email" id="email" placeholder="email" minlength="2" maxlength="30" required>
        <label for="email">Email address</label>
    </div>

    <div class="form-floating mb-3">
        <input type="password" class="form-control" name="password" id="password" placeholder="password" minlength="2" maxlength="20" required>
        <label for="password">Password</label>
    </div>

    <button type="submit" class="btn btn-warning w-100">Register</button>
    <a href="{{ url_for('home_view.home') }}" class="back-link">Back to Home</a>
</form>
{% endblock content %}

source/templates/vacation_details.html
{% extends "layout.html" %}

{% block title %}Vacation Details{% endblock title %}

{% block content %}
<div class="details-container">
    <div class="details-textbox">
        <h1 class="details-header-style">#{{ vacation.vacation_id }} - {{ vacation.country_id }}</h1>
        <p class="details-dates-style">{{ vacation.vacation_start }} - {{ vacation.vacation_end }}</p>
        <p class="details-info-style">{{ vacation.vacation_info }}</p>
        <img src="{{ url_for('vacations_view.get_image', image_name=(vacation.pic_name if vacation.pic_name else '---')) }}" alt="Vacation Image" height="300" width="300">
    </div>
    <img src="{{ url_for('static', filename='images/Chocotours_Logo.png') }}" class="details-logo" alt="Logo Image">
</div>
<a href="{{ url_for('vacations_view.list') }}" class="back-link">All vacations</a>
{% endblock content %}

source/templates/vacations.html
{% extends "layout.html" %}

{% block title %}Vacations{% endblock title %}

{% block content %}
<div class="vacations-container p-3 mb-3">
    <div class="vacations-title">
        <h1><strong>Our vacations</strong></h1>
    </div>

    <div class="flash-message">
        <h2 class="flash-message">{{ get_flashed_messages()[0] }}</h2>
        
        {% if current_user.roleId == admin %}
        <a href="{{ url_for('vacations_view.insert') }}" class="btn btn-light d-flex justify-content-center align-items-center add-btn" role="button">
            ➕
        </a>
        {% endif %}
    </div>

    <div class="d-flex flex-wrap justify-content-start">
        {% for v in vacations %}
        <div class="card bg-dark text-white m-2" style="width: 18rem; position: relative;">
            {% if v.vacation_id in user_liked_vacations %}
            <div class="is-liked">❤️</div>
            {% endif %}

            <img src="{{ url_for('vacations_view.get_image', image_name=(v.pic_name if v.pic_name else '---')) }}" class="card-img" alt="Vacation Image">
            
            <div class="card-img-overlay d-flex flex-column justify-content-between">
                <h4 class="country-name text-center">{{ v.country_id }}</h4>
                <span class="vacation-dates position-absolute top-0 end-0 mt-2 me-2">🗓️{{ v.vacation_start }} ➡️ {{ v.vacation_end }}</span>

                {% if current_user.roleId == user %}
                <form method="post" class="d-flex justify-content-start">
                    <input type="hidden" id="user_id" name="user_id" value="{{ current_user['userId'] }}">
                    <input type="hidden" id="vacation_id" name="vacation_id" value="{{ v.vacation_id }}">
                    <button type="submit" class="like-button btn btn-danger mt-auto mb-2 ms-2">❤️ {{ likes[v.vacation_id] or 0 }}</button>
                </form>
                {% endif %}

                {% if current_user.roleId == admin %}
                <div class="btn-group btn-group-sm" style="margin-bottom: 3px;">
                    <a onclick="confirmation()" href="{{ url_for('vacations_view.delete', vacation_id=v.vacation_id) }}" class="btn btn-danger" title="Delete">🗑️</a>
                    <a href="{{ url_for('vacations_view.edit', vacation_id=v.vacation_id) }}" class="btn btn-success" title="Update">♻️</a>
                </div>
                {% endif %}

                <a href="{{ url_for('vacations_view.details', vacation_id=v.vacation_id) }}" class="price-button btn btn-warning w-100">${{ v.price }}</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}